/*
 <a href="http://en.wikipedia.org/wiki/MIT_License">MIT</a>.
 @copyright All rights reserved <a href="http://www.webitup.fr">? Web It Up</a>
 @name https://github.com/jsBoot/spitfire.js/blob/master/src/loader.js#52-3657ff5469197138e12e590799bc63fccad52efb
*/
'use strict';(function(h){function m(d,a){var b=/^\w+\:\/\//;/^\/\/\/?/.test(d)?d=location.protocol+d:!b.test(d)&&d.charAt(0)!="/"&&(d=(a||"")+d);return b.test(d)?d:(d.charAt(0)=="/"?x:y)+d}function q(d,b){for(var a in d)d.hasOwnProperty(a)&&(b[a]=d[a]);return b}function n(d,a,b,c){d.onload=d.onreadystatechange=function(){if(!(d.readyState&&d.readyState!="complete"&&d.readyState!="loaded"||a[b]))d.onload=d.onreadystatechange=null,c()}}function u(d){d.ready=d.finished=true;for(var a=0;a<d.finished_listeners.length;a++)d.finished_listeners[a]();
d.ready_listeners=[];d.finished_listeners=[]}function b(d,a,b,c,h){var l=function(){var f,e=a.real_src,r;if("item"in j){if(!j[0]){setTimeout(l,25);return}j=j[0]}f=document.createElement("script");if(a.type)f.type=a.type;if(a.charset)f.charset=a.charset;h?v?(d[k]&&o("start script preload: "+e),b.elem=f,z?(f.preload=true,f.onpreload=c):f.onreadystatechange=function(){f.readyState=="loaded"&&c()},f.src=e):h&&e.indexOf(x)===0&&d[g]?(r=new XMLHttpRequest,d[k]&&o("start script preload (xhr): "+e),r.onreadystatechange=
function(){if(r.readyState==4)r.onreadystatechange=function(){},b.text=r.responseText+"\n//@ sourceURL="+e,c()},r.open("GET",e),r.send()):(d[k]&&o("start script preload (cache): "+e),f.type="text/cache-script",n(f,b,"ready",function(){j.removeChild(f);c()}),f.src=e,j.insertBefore(f,j.firstChild)):(A?(d[k]&&o("start script load (ordered async): "+e),f.async=false):d[k]&&o("start script load: "+e),n(f,b,"finished",c),f.src=e,j.insertBefore(f,j.firstChild))};setTimeout(l,0)}function a(){function d(a,
d,b){function c(){i!==null&&(i=null,u(b))}var i;if(!f[d.src].finished){if(!a[l])f[d.src].finished=true;i=b.elem||document.createElement("script");if(d.type)i.type=d.type;if(d.charset)i.charset=d.charset;n(i,b,"finished",c);b.elem?b.elem=null:b.text?(i.onload=i.onreadystatechange=null,i.text=b.text):i.src=d.real_src;j.insertBefore(i,j.firstChild);b.text&&c()}}function F(a,c,h,g){var i,e,k=function(){c.ready_cb(c,function(){d(a,c,i)})},j=function(){c.finished_cb(c,h)};c.src=m(c.src,a[B]);c.real_src=
c.src+(a[C]?(/\?.*$/.test(c.src)?"&_":"?_")+~~(Math.random()*1E9)+"=":"");f[c.src]||(f[c.src]={items:[],finished:false});e=f[c.src].items;a[l]||e.length===0?(i=e[e.length]={ready:false,finished:false,ready_listeners:[k],finished_listeners:[j]},b(a,c,i,g?function(){i.ready=true;for(var a=0;a<i.ready_listeners.length;a++)i.ready_listeners[a]();i.ready_listeners=[]}:function(){u(i)},g)):(i=e[0],i.finished?j():i.finished_listeners.push(j))}function w(){function a(c,d){i[k]&&o("script preload finished: "+
c.real_src);c.ready=true;c.exec_trigger=d;b()}function d(a,c){i[k]&&o("script execution finished: "+a.real_src);a.ready=a.finished=true;a.exec_trigger=null;for(var f=0;f<c.scripts.length;f++)if(!c.scripts[f].finished)return;c.finished=true;b()}function b(){for(;e<f.length;)if(Object.prototype.toString.call(f[e])=="[object Function]"){i[k]&&o("$LAB.wait() executing: "+f[e]);try{f[e++]()}catch(a){i[k]&&D("$LAB.wait() error caught: ",a)}}else{if(!f[e].finished){for(var c=f[e],d=false,l=0;l<c.scripts.length;l++)if(c.scripts[l].ready&&
c.scripts[l].exec_trigger)d=true,c.scripts[l].exec_trigger(),c.scripts[l].exec_trigger=null;if(d)continue;break}e++}e==f.length&&(g=h=false)}var c,i=q(p,{}),f=[],e=0,h=false,g;c={script:function(){for(var b=0;b<arguments.length;b++){var e=arguments[b],l=arguments[b],j=void 0;Object.prototype.toString.call(e)=="[object Array]"||(l=[e]);for(var k=0;k<l.length;k++){if(!g||!g.scripts)f.push(g={scripts:[],finished:true});e=l[k];Object.prototype.toString.call(e)=="[object Function]"&&(e=e());if(e)Object.prototype.toString.call(e)==
"[object Array]"?(j=[].slice.call(e),j.unshift(k,1),[].splice.apply(l,j),k--):(typeof e=="string"&&(e={src:e}),e=q(e,{ready:false,ready_cb:a,finished:false,finished_cb:d}),g.finished=false,g.scripts.push(e),F(i,e,g,t&&h),h=true,i[E]&&c.wait())}}return c},wait:function(){if(arguments.length>0){for(var a=0;a<arguments.length;a++)f.push(arguments[a]);g=f[f.length-1]}else g=false;b();return c}};return{script:c.script,wait:c.wait,setOptions:function(a){q(a,i);return c}}}var p={},t=v||G,s=[],f={},e;p[g]=
true;p[E]=false;p[l]=false;p[C]=false;p[k]=false;p[B]="";return e={setGlobalDefaults:function(a){q(a,p);return e},setOptions:function(){return w().setOptions.apply(null,arguments)},script:function(){return w().script.apply(null,arguments)},wait:function(){return w().wait.apply(null,arguments)},queueScript:function(){s[s.length]={type:"script",args:[].slice.call(arguments)};return e},queueWait:function(){s[s.length]={type:"wait",args:[].slice.call(arguments)};return e},runQueue:function(){for(var a=
e,c=s.length,b;--c>=0;)b=s.shift(),a=a[b.type].apply(null,b.args);return a},noConflict:function(){h.$LAB=c;return e},sandbox:function(){return a()}}}var c=h.$LAB,g="UseLocalXHR",E="AlwaysPreserveOrder",l="AllowDuplicates",C="CacheBust",k="Debug",B="BasePath",y=/^[^?#]*\//.exec(location.href)[0],x=/^\w+\:\/\/\/?[^\/]+/.exec(y)[0],j=document.head||document.getElementsByTagName("head"),H=h.opera&&Object.prototype.toString.call(h.opera)=="[object Opera]"||"MozAppearance"in document.documentElement.style,
o=function(){},D=o,t=document.createElement("script"),z=typeof t.preload=="boolean",v=z||t.readyState&&t.readyState=="uninitialized",A=!v&&t.async===true,G=!v&&!A&&!H;if(h.console&&h.console.log){if(!h.console.error)h.console.error=h.console.log;o=function(a){h.console.log(a)};D=function(a,c){h.console.error(a,c)}}h.$LAB=a();(function(a,c,b){if((document.readyState===null||document.readyState===void 0)&&document[a])document.readyState="loading",document[a](c,b=function(){document.removeEventListener(c,
b,false);document.readyState="complete"},false)})("addEventListener","DOMContentLoaded")})(this);
(function(){var h;typeof head!="undefined"&&(h=function(){return function(b,a){b.push(a);return head.js.apply(head.js,b)}});typeof YUI!="undefined"&&(h=function(){var b;YUI().use("get",function(a){b=a});b.Get.options.async=true;return function(){b.Get.js.apply(b.Get,arguments)}});typeof yepnope!="undefined"&&(h=function(){return function(b,a){var c=b[b.length-1];yepnope({load:b,callback:function(b){c==b&&a()}})}});typeof requirejs!="undefined"&&(h=function(){return function(b,a){requirejs(b,a)}});
var m;typeof $LAB!="undefined"&&(m=function(){var b=$LAB.sandbox();this.script=function(a){b=b.script(a);return this};this.wait=function(a){b=a?b.wait(a):b.wait();return this}});m||(m=function(){var b=null,a=[],c=false,g=h(),m=function(){if(!c&&(c=a.shift()))if(c.uris.length)g(c.uris,function(a){var b=c.callback;c=false;b&&b(a);m()});else{var b=c.callback;c=false;b&&b();m()}};this.script=function(c){b&&clearTimeout(b);a.length||a.push({uris:[],callback:false});a[a.length-1].uris.push(c);b=setTimeout(m,
1);return this};this.wait=function(b){var g=a.length?a[a.length-1]:false;c&&(g=c);if(!g)return b&&b(),this;g.callback?a.push({uris:[],callback:b}):(g.callback=b,a.push({uris:[],callback:false}));return this}});m.prototype.fork=function(){return new m};m.prototype.base=function(b){for(var a=document.getElementsByTagName("script"),c,b=RegExp(b),g=0,h;g<a.length;h=a[g].getAttribute("src"),g++)if(h&&b.test(h)){c=h.split("/");c.pop();c=c.join("/");break}return c};var q=1,n=null;m.prototype.style=function(b,
a){var c=document.getElementsByTagName("head")[0],g=document.createElement("link");g.setAttribute("type","text/css");g.setAttribute("rel","stylesheet");g.setAttribute("data-spitfire-index",q);a&&g.setAttribute("media",a);g.setAttribute("href",b);if(!n)n=c.lastChild;!n||!n.nextSibling?c.appendChild(g):c.insertBefore(g,n.nextSibling);n=g;q++};var u=typeof define==="function"&&define.amd;if(u||typeof exports=="object"&&exports)u&&define("Spitfire/loader",new m);else{if(!("Spitfire"in this))this.Spitfire=
{};this.Spitfire.loader=new m}}).apply(this);
