/*
 <a href="http://en.wikipedia.org/wiki/MIT_License">MIT</a>.
 @copyright All rights reserved <a href="http://www.webitup.fr">? Web It Up</a>
 @name https://github.com/jsBoot/spitfire.js/blob/master/src/loader.js#52-3657ff5469197138e12e590799bc63fccad52efb
*/
'use strict';(function(){var g;typeof head!="undefined"&&(g=function(){return function(a,b){a.push(b);return head.js.apply(head.js,a)}});typeof YUI!="undefined"&&(g=function(){var a;YUI().use("get",function(b){a=b});a.Get.options.async=true;return function(){a.Get.js.apply(a.Get,arguments)}});typeof yepnope!="undefined"&&(g=function(){return function(a,b){var c=a[a.length-1];yepnope({load:a,callback:function(a){c==a&&b()}})}});typeof requirejs!="undefined"&&(g=function(){return function(a,b){requirejs(a,
b)}});var e;typeof $LAB!="undefined"&&(e=function(){var a=$LAB.sandbox();this.script=function(b){a=a.script(b);return this};this.wait=function(b){a=b?a.wait(b):a.wait();return this}});e||(e=function(){var a=null,b=[],c=false,d=g(),e=function(){if(!c&&(c=b.shift()))if(c.uris.length)d(c.uris,function(a){var b=c.callback;c=false;b&&b(a);e()});else{var a=c.callback;c=false;a&&a();e()}};this.script=function(c){a&&clearTimeout(a);b.length||b.push({uris:[],callback:false});b[b.length-1].uris.push(c);a=setTimeout(e,
1);return this};this.wait=function(a){var d=b.length?b[b.length-1]:false;c&&(d=c);if(!d)return a&&a(),this;d.callback?b.push({uris:[],callback:a}):(d.callback=a,b.push({uris:[],callback:false}));return this}});e.prototype.fork=function(){return new e};e.prototype.base=function(a){for(var b=document.getElementsByTagName("script"),c,a=RegExp(a),d=0,e;d<b.length;e=b[d].getAttribute("src"),d++)if(e&&a.test(e)){c=e.split("/");c.pop();c=c.join("/");break}return c};var h=1,f=null;e.prototype.style=function(a,
b){var c=document.getElementsByTagName("head")[0],d=document.createElement("link");d.setAttribute("type","text/css");d.setAttribute("rel","stylesheet");d.setAttribute("data-spitfire-index",h);b&&d.setAttribute("media",b);d.setAttribute("href",a);if(!f)f=c.lastChild;!f||!f.nextSibling?c.appendChild(d):c.insertBefore(d,f.nextSibling);f=d;h++};var i=typeof define==="function"&&define.amd;if(i||typeof exports=="object"&&exports)i&&define("Spitfire/loader",new e);else{if(!("Spitfire"in this))this.Spitfire=
{};this.Spitfire.loader=new e}}).apply(this);
