/*
 <a href="http://en.wikipedia.org/wiki/MIT_License">MIT</a>.
 @copyright All rights reserved <a href="http://www.webitup.fr">? Web It Up</a>
 @name https://github.com/jsBoot/spitfire.js/blob/master/src/shimer.js#52-3657ff5469197138e12e590799bc63fccad52efb
 <a href="http://en.wikipedia.org/wiki/MIT_License">MIT</a>.
 @copyright All rights reserved <a href="http://www.webitup.fr">? Web It Up</a>
 @name https://github.com/jsBoot/spitfire.js/blob/master/src/loader.js#52-3657ff5469197138e12e590799bc63fccad52efb
*/
'use strict';(function(e){function a(a,c){var b=/^\w+\:\/\//;/^\/\/\/?/.test(a)?a=location.protocol+a:!b.test(a)&&a.charAt(0)!="/"&&(a=(c||"")+a);return b.test(a)?a:(a.charAt(0)=="/"?x:y)+a}function m(a,c){for(var b in a)a.hasOwnProperty(b)&&(c[b]=a[b]);return c}function h(a,c,b,g){a.onload=a.onreadystatechange=function(){if(!(a.readyState&&a.readyState!="complete"&&a.readyState!="loaded"||c[b]))a.onload=a.onreadystatechange=null,g()}}function p(a){a.ready=a.finished=true;for(var c=0;c<a.finished_listeners.length;c++)a.finished_listeners[c]();
a.ready_listeners=[];a.finished_listeners=[]}function g(a,b,g,f,d){var e=function(){var i,j=b.real_src,q;if("item"in l){if(!l[0]){setTimeout(e,25);return}l=l[0]}i=document.createElement("script");if(b.type)i.type=b.type;if(b.charset)i.charset=b.charset;d?v?(a[k]&&n("start script preload: "+j),g.elem=i,z?(i.preload=true,i.onpreload=f):i.onreadystatechange=function(){i.readyState=="loaded"&&f()},i.src=j):d&&j.indexOf(x)===0&&a[c]?(q=new XMLHttpRequest,a[k]&&n("start script preload (xhr): "+j),q.onreadystatechange=
function(){if(q.readyState==4)q.onreadystatechange=function(){},g.text=q.responseText+"\n//@ sourceURL="+j,f()},q.open("GET",j),q.send()):(a[k]&&n("start script preload (cache): "+j),i.type="text/cache-script",h(i,g,"ready",function(){l.removeChild(i);f()}),i.src=j,l.insertBefore(i,l.firstChild)):(A?(a[k]&&n("start script load (ordered async): "+j),i.async=false):a[k]&&n("start script load: "+j),h(i,g,"finished",f),i.src=j,l.insertBefore(i,l.firstChild))};setTimeout(e,0)}function b(){function D(a,
c,b){function g(){f!==null&&(f=null,p(b))}var f;if(!i[c.src].finished){if(!a[j])i[c.src].finished=true;f=b.elem||document.createElement("script");if(c.type)f.type=c.type;if(c.charset)f.charset=c.charset;h(f,b,"finished",g);b.elem?b.elem=null:b.text?(f.onload=f.onreadystatechange=null,f.text=b.text):f.src=c.real_src;l.insertBefore(f,l.firstChild);b.text&&g()}}function E(c,b,f,d){var e,k,m=function(){b.ready_cb(b,function(){D(c,b,e)})},h=function(){b.finished_cb(b,f)};b.src=a(b.src,c[B]);b.real_src=
b.src+(c[t]?(/\?.*$/.test(b.src)?"&_":"?_")+~~(Math.random()*1E9)+"=":"");i[b.src]||(i[b.src]={items:[],finished:false});k=i[b.src].items;c[j]||k.length===0?(e=k[k.length]={ready:false,finished:false,ready_listeners:[m],finished_listeners:[h]},g(c,b,e,d?function(){e.ready=true;for(var a=0;a<e.ready_listeners.length;a++)e.ready_listeners[a]();e.ready_listeners=[]}:function(){p(e)},d)):(e=k[0],e.finished?h():e.finished_listeners.push(h))}function w(){function a(b,f){e[k]&&n("script preload finished: "+
b.real_src);b.ready=true;b.exec_trigger=f;c()}function b(a,f){e[k]&&n("script execution finished: "+a.real_src);a.ready=a.finished=true;a.exec_trigger=null;for(var g=0;g<f.scripts.length;g++)if(!f.scripts[g].finished)return;f.finished=true;c()}function c(){for(;d<j.length;)if(Object.prototype.toString.call(j[d])=="[object Function]"){e[k]&&n("$LAB.wait() executing: "+j[d]);try{j[d++]()}catch(a){e[k]&&C("$LAB.wait() error caught: ",a)}}else{if(!j[d].finished){for(var b=j[d],f=false,g=0;g<b.scripts.length;g++)if(b.scripts[g].ready&&
b.scripts[g].exec_trigger)f=true,b.scripts[g].exec_trigger(),b.scripts[g].exec_trigger=null;if(f)continue;break}d++}d==j.length&&(h=i=false)}var g,e=m(o,{}),j=[],d=0,i=false,h;g={script:function(){for(var c=0;c<arguments.length;c++){var d=arguments[c],k=arguments[c],t=void 0;Object.prototype.toString.call(d)=="[object Array]"||(k=[d]);for(var l=0;l<k.length;l++){if(!h||!h.scripts)j.push(h={scripts:[],finished:true});d=k[l];Object.prototype.toString.call(d)=="[object Function]"&&(d=d());if(d)Object.prototype.toString.call(d)==
"[object Array]"?(t=[].slice.call(d),t.unshift(l,1),[].splice.apply(k,t),l--):(typeof d=="string"&&(d={src:d}),d=m(d,{ready:false,ready_cb:a,finished:false,finished_cb:b}),h.finished=false,h.scripts.push(d),E(e,d,h,u&&i),i=true,e[f]&&g.wait())}}return g},wait:function(){if(arguments.length>0){for(var a=0;a<arguments.length;a++)j.push(arguments[a]);h=j[j.length-1]}else h=false;c();return g}};return{script:g.script,wait:g.wait,setOptions:function(a){m(a,e);return g}}}var o={},u=v||F,s=[],i={},r;o[c]=
true;o[f]=false;o[j]=false;o[t]=false;o[k]=false;o[B]="";return r={setGlobalDefaults:function(a){m(a,o);return r},setOptions:function(){return w().setOptions.apply(null,arguments)},script:function(){return w().script.apply(null,arguments)},wait:function(){return w().wait.apply(null,arguments)},queueScript:function(){s[s.length]={type:"script",args:[].slice.call(arguments)};return r},queueWait:function(){s[s.length]={type:"wait",args:[].slice.call(arguments)};return r},runQueue:function(){for(var a=
r,b=s.length,c;--b>=0;)c=s.shift(),a=a[c.type].apply(null,c.args);return a},noConflict:function(){e.$LAB=d;return r},sandbox:function(){return b()}}}var d=e.$LAB,c="UseLocalXHR",f="AlwaysPreserveOrder",j="AllowDuplicates",t="CacheBust",k="Debug",B="BasePath",y=/^[^?#]*\//.exec(location.href)[0],x=/^\w+\:\/\/\/?[^\/]+/.exec(y)[0],l=document.head||document.getElementsByTagName("head"),G=e.opera&&Object.prototype.toString.call(e.opera)=="[object Opera]"||"MozAppearance"in document.documentElement.style,
n=function(){},C=n,u=document.createElement("script"),z=typeof u.preload=="boolean",v=z||u.readyState&&u.readyState=="uninitialized",A=!v&&u.async===true,F=!v&&!A&&!G;if(e.console&&e.console.log){if(!e.console.error)e.console.error=e.console.log;n=function(a){e.console.log(a)};C=function(a,b){e.console.error(a,b)}}e.$LAB=b();(function(a,b,c){if((document.readyState===null||document.readyState===void 0)&&document[a])document.readyState="loading",document[a](b,c=function(){document.removeEventListener(b,
c,false);document.readyState="complete"},false)})("addEventListener","DOMContentLoaded")})(this);
(function(){var e;typeof head!="undefined"&&(e=function(){return function(a,b){a.push(b);return head.js.apply(head.js,a)}});typeof YUI!="undefined"&&(e=function(){var a;YUI().use("get",function(b){a=b});a.Get.options.async=true;return function(){a.Get.js.apply(a.Get,arguments)}});typeof yepnope!="undefined"&&(e=function(){return function(a,b){var d=a[a.length-1];yepnope({load:a,callback:function(a){d==a&&b()}})}});typeof requirejs!="undefined"&&(e=function(){return function(a,b){requirejs(a,b)}});
var a;typeof $LAB!="undefined"&&(a=function(){var a=$LAB.sandbox();this.script=function(b){a=a.script(b);return this};this.wait=function(b){a=b?a.wait(b):a.wait();return this}});a||(a=function(){var a=null,b=[],d=false,c=e(),f=function(){if(!d&&(d=b.shift()))if(d.uris.length)c(d.uris,function(a){var b=d.callback;d=false;b&&b(a);f()});else{var a=d.callback;d=false;a&&a();f()}};this.script=function(c){a&&clearTimeout(a);b.length||b.push({uris:[],callback:false});b[b.length-1].uris.push(c);a=setTimeout(f,
1);return this};this.wait=function(a){var c=b.length?b[b.length-1]:false;d&&(c=d);if(!c)return a&&a(),this;c.callback?b.push({uris:[],callback:a}):(c.callback=a,b.push({uris:[],callback:false}));return this}});a.prototype.fork=function(){return new a};a.prototype.base=function(a){for(var b=document.getElementsByTagName("script"),d,a=RegExp(a),c=0,f;c<b.length;f=b[c].getAttribute("src"),c++)if(f&&a.test(f)){d=f.split("/");d.pop();d=d.join("/");break}return d};var m=1,h=null;a.prototype.style=function(a,
b){var d=document.getElementsByTagName("head")[0],c=document.createElement("link");c.setAttribute("type","text/css");c.setAttribute("rel","stylesheet");c.setAttribute("data-spitfire-index",m);b&&c.setAttribute("media",b);c.setAttribute("href",a);if(!h)h=d.lastChild;!h||!h.nextSibling?d.appendChild(c):d.insertBefore(c,h.nextSibling);h=c;m++};var p=typeof define==="function"&&define.amd;if(p||typeof exports=="object"&&exports)p&&define("Spitfire/loader",new a);else{if(!("Spitfire"in this))this.Spitfire=
{};this.Spitfire.loader=new a}}).apply(this);
(function(){var e=typeof define==="function"&&define.amd,a=typeof exports=="object"&&exports;e||a?e&&define("Spitfire",a={}):a=this.Spitfire||(this.Spitfire={});var m={},h=[];a.add=function(a,b){b in m||(m[b]=[]);m[b].push(a)};a.use=function(a){if(!a||!(a in m))throw"INVALID_CATEGORY";for(var b=0;b<m[a].length;b++)h.push(m[a][b])};a.boot=function(a){for(var b=[],d=0,e;d<h.length&&(e=h[d]);d++)e.test&&(e.patch?e.patch():b.push("burnscars/"+e.uri+(a?".js":"-min.js")));return b};a.XHR="xhr";a.add({test:true,
uri:"xmlhttprequest"},a.XHR);a.JSON="json";a.add({test:true,uri:"json3"},a.JSON);a.UNSAFE="unsafe";a.add({test:!Function.isGenerator,uri:"function.isgenerator"},a.UNSAFE);a.add({test:!Object.preventExtensions||!Object.isSealed||!Object.isFrozen||!Object.seal||!Object.freeze,uri:"es5-sham"},a.UNSAFE);a.SAFE="safe";var e=[].unshift("test")===void 0||[1,2].splice(0).length!=2||!Array.isArray||!Array.prototype.forEach||!Array.prototype.map||!Array.prototype.filter||!Array.prototype.every||!Array.prototype.some||
!Array.prototype.reduce||!Array.prototype.reduceRight||!Array.prototype.indexOf||[0,1].indexOf(1,2)!=-1||!Array.prototype.lastIndexOf||[0,1].lastIndexOf(0,-3)!=-1,p=!Function.prototype.bind,g=!Object.keys,b=!Date.now||!Date.prototype.toISOString||!Date.parse||(new Date(-621987552E5)).toISOString().indexOf("-000001")===-1||function(){var a=false;try{a=Date.prototype.toJSON&&(new Date(NaN)).toJSON()===null&&(new Date(-621987552E5)).toJSON().indexOf("-000001")!==-1&&Date.prototype.toJSON.call({toISOString:function(){return true}})}catch(b){}return!a}(),
d=!!"0".split(void 0,0).length||"".substr&&"0b".substr(-1)!=="b"||!String.prototype.trim||"\t\n\u000b\u000c\r \u00a0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u3000\u2028"+"\u2029\ufeff".trim(),e=e||p||g||b||d;a.add({test:Object.freeze&&function(){try{Object.freeze(function(){})}catch(a){return true}return false}(),patch:function(){Object.freeze=function(a){return function(b){return typeof b=="function"?b:a(b)}}(Object.freeze)}},a.SAFE);a.add({test:typeof TypeError==
"undefined",patch:function(){window.TypeError=Error||function(){}}},a.SAFE);a.add({test:!Object.getPrototypeOf,uri:"object.getprototypeof"},a.SAFE);a.add({test:!Object.getOwnPropertyDescriptor,uri:"object.getownpropertydescriptor"},a.SAFE);a.add({test:!Object.getOwnPropertyNames,uri:"object.getownpropertynames"},a.SAFE);a.add({test:!Object.create,uri:"object.create"},a.SAFE);a.add({test:!Object.defineProperty,uri:"object.defineproperty"},a.SAFE);a.add({test:!Object.defineProperties,uri:"object.defineproperties"},
a.SAFE);a.add({test:!Object.isExtensible,uri:"object.isextensible"},a.SAFE);a.add({test:!window.addEventListener,uri:"events"},a.SAFE);a.add({test:!window.localStorage,uri:"localstorage"},a.SAFE);a.add({test:!navigator.geolocation,uri:"geolocation"},a.SAFE);a.add({test:e,uri:"es5-shim"},a.SAFE);a.add({test:!window.JSON,uri:"json3"},a.SAFE);a.add({test:!window.XMLHttpRequest,uri:"xmlhttprequest"},a.SAFE);a.add({test:!window.console||eval("/*@cc_on @_jscript_version <= 9@*/")||!function(){for(var a=
true,b="log,debug,info,warn,error,assert".split(","),d=0;d<b.length;d++)a&=!!window.console[b[d]];return a}(),uri:"console"},a.SAFE);a.use(a.SAFE);a.add({test:!window.requestAnimationFrame||!window.cancelAnimationFrame,uri:"animationframe"},a.SAFE);a.add({test:!Array.from||!Array.of,uri:"es6.array"},a.SAFE);a.add({test:!Math.acosh||!Math.asinh||!Math.atanh||!Math.cosh||!Math.sinh||!Math.tanh||!Math.expm1,uri:"es6.math"},a.SAFE);a.add({test:!Number.isFinite||!Number.isInteger||!Number.isNaN||!Number.toInteger,
uri:"es6.number"},a.SAFE);a.add({test:!Object.getOwnPropertyDescriptors||!Object.getPropertyDescriptor||!Object.getPropertyNames||!Object.is||!Object.isnt,uri:"es6.object"},a.SAFE);a.add({test:!String.prototype.repeat||!String.prototype.startsWith||!String.prototype.endsWith||!String.prototype.contains,uri:"es6.string"},a.SAFE);setTimeout(function(a){if(!a){var b=window.setTimeout;window.setTimeout=function(a,d){var c=Array.prototype.slice.call(arguments);c.shift();c.shift();b(function(){a.apply(this,
c)},d)}}},1,true)}).apply(this);
