/*
 <a href="http://en.wikipedia.org/wiki/MIT_License">MIT</a>.
 @copyright All rights reserved <a href="http://www.webitup.fr">? Web It Up</a>
 @name https://github.com/jsBoot/spitfire.js/blob/master/src/shimer.js#52-3657ff5469197138e12e590799bc63fccad52efb
 <a href="http://en.wikipedia.org/wiki/MIT_License">MIT</a>.
 @copyright All rights reserved <a href="http://www.webitup.fr">? Web It Up</a>
 @name https://github.com/jsBoot/spitfire.js/blob/master/src/loader.js#52-3657ff5469197138e12e590799bc63fccad52efb
*/
'use strict';(function(){var e;typeof head!="undefined"&&(e=function(){return function(a,b){a.push(b);return head.js.apply(head.js,a)}});typeof YUI!="undefined"&&(e=function(){var a;YUI().use("get",function(b){a=b});a.Get.options.async=true;return function(){a.Get.js.apply(a.Get,arguments)}});typeof yepnope!="undefined"&&(e=function(){return function(a,b){var c=a[a.length-1];yepnope({load:a,callback:function(a){c==a&&b()}})}});typeof requirejs!="undefined"&&(e=function(){return function(a,b){requirejs(a,
b)}});var a;typeof $LAB!="undefined"&&(a=function(){var a=$LAB.sandbox();this.script=function(b){a=a.script(b);return this};this.wait=function(b){a=b?a.wait(b):a.wait();return this}});a||(a=function(){var a=null,b=[],c=false,d=e(),h=function(){if(!c&&(c=b.shift()))if(c.uris.length)d(c.uris,function(a){var d=c.callback;c=false;d&&d(a);h()});else{var a=c.callback;c=false;a&&a();h()}};this.script=function(d){a&&clearTimeout(a);b.length||b.push({uris:[],callback:false});b[b.length-1].uris.push(d);a=setTimeout(h,
1);return this};this.wait=function(a){var d=b.length?b[b.length-1]:false;c&&(d=c);if(!d)return a&&a(),this;d.callback?b.push({uris:[],callback:a}):(d.callback=a,b.push({uris:[],callback:false}));return this}});a.prototype.fork=function(){return new a};a.prototype.base=function(a){for(var b=document.getElementsByTagName("script"),c,a=RegExp(a),d=0,h;d<b.length;h=b[d].getAttribute("src"),d++)if(h&&a.test(h)){c=h.split("/");c.pop();c=c.join("/");break}return c};var g=1,f=null;a.prototype.style=function(a,
b){var c=document.getElementsByTagName("head")[0],d=document.createElement("link");d.setAttribute("type","text/css");d.setAttribute("rel","stylesheet");d.setAttribute("data-spitfire-index",g);b&&d.setAttribute("media",b);d.setAttribute("href",a);if(!f)f=c.lastChild;!f||!f.nextSibling?c.appendChild(d):c.insertBefore(d,f.nextSibling);f=d;g++};var i=typeof define==="function"&&define.amd;if(i||typeof exports=="object"&&exports)i&&define("Spitfire/loader",new a);else{if(!("Spitfire"in this))this.Spitfire=
{};this.Spitfire.loader=new a}}).apply(this);
(function(){var e=typeof define==="function"&&define.amd,a=typeof exports=="object"&&exports;e||a?e&&define("Spitfire",a={}):a=this.Spitfire||(this.Spitfire={});var g={},f=[];a.add=function(a,b){b in g||(g[b]=[]);g[b].push(a)};a.use=function(a){if(!a||!(a in g))throw"INVALID_CATEGORY";for(var b=0;b<g[a].length;b++)f.push(g[a][b])};a.boot=function(a){for(var b=[],c=0,e;c<f.length&&(e=f[c]);c++)e.test&&(e.patch?e.patch():b.push("burnscars/"+e.uri+(a?".js":"-min.js")));return b};a.XHR="xhr";a.add({test:true,
uri:"xmlhttprequest"},a.XHR);a.JSON="json";a.add({test:true,uri:"json3"},a.JSON);a.UNSAFE="unsafe";a.add({test:!Function.isGenerator,uri:"function.isgenerator"},a.UNSAFE);a.add({test:!Object.preventExtensions||!Object.isSealed||!Object.isFrozen||!Object.seal||!Object.freeze,uri:"es5-sham"},a.UNSAFE);a.SAFE="safe";var e=[].unshift("test")===void 0||[1,2].splice(0).length!=2||!Array.isArray||!Array.prototype.forEach||!Array.prototype.map||!Array.prototype.filter||!Array.prototype.every||!Array.prototype.some||
!Array.prototype.reduce||!Array.prototype.reduceRight||!Array.prototype.indexOf||[0,1].indexOf(1,2)!=-1||!Array.prototype.lastIndexOf||[0,1].lastIndexOf(0,-3)!=-1,i=!Function.prototype.bind,j=!Object.keys,b=!Date.now||!Date.prototype.toISOString||!Date.parse||(new Date(-621987552E5)).toISOString().indexOf("-000001")===-1||function(){var a=false;try{a=Date.prototype.toJSON&&(new Date(NaN)).toJSON()===null&&(new Date(-621987552E5)).toJSON().indexOf("-000001")!==-1&&Date.prototype.toJSON.call({toISOString:function(){return true}})}catch(b){}return!a}(),
c=!!"0".split(void 0,0).length||"".substr&&"0b".substr(-1)!=="b"||!String.prototype.trim||"\t\n\u000b\u000c\r \u00a0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u3000\u2028"+"\u2029\ufeff".trim(),e=e||i||j||b||c;a.add({test:Object.freeze&&function(){try{Object.freeze(function(){})}catch(a){return true}return false}(),patch:function(){Object.freeze=function(a){return function(b){return typeof b=="function"?b:a(b)}}(Object.freeze)}},a.SAFE);a.add({test:typeof TypeError==
"undefined",patch:function(){window.TypeError=Error||function(){}}},a.SAFE);a.add({test:!Object.getPrototypeOf,uri:"object.getprototypeof"},a.SAFE);a.add({test:!Object.getOwnPropertyDescriptor,uri:"object.getownpropertydescriptor"},a.SAFE);a.add({test:!Object.getOwnPropertyNames,uri:"object.getownpropertynames"},a.SAFE);a.add({test:!Object.create,uri:"object.create"},a.SAFE);a.add({test:!Object.defineProperty,uri:"object.defineproperty"},a.SAFE);a.add({test:!Object.defineProperties,uri:"object.defineproperties"},
a.SAFE);a.add({test:!Object.isExtensible,uri:"object.isextensible"},a.SAFE);a.add({test:!window.addEventListener,uri:"events"},a.SAFE);a.add({test:!window.localStorage,uri:"localstorage"},a.SAFE);a.add({test:!navigator.geolocation,uri:"geolocation"},a.SAFE);a.add({test:e,uri:"es5-shim"},a.SAFE);a.add({test:!window.JSON,uri:"json3"},a.SAFE);a.add({test:!window.XMLHttpRequest,uri:"xmlhttprequest"},a.SAFE);a.add({test:!window.console||eval("/*@cc_on @_jscript_version <= 9@*/")||!function(){for(var a=
true,b="log,debug,info,warn,error,assert".split(","),c=0;c<b.length;c++)a&=!!window.console[b[c]];return a}(),uri:"console"},a.SAFE);a.use(a.SAFE);a.add({test:!window.requestAnimationFrame||!window.cancelAnimationFrame,uri:"animationframe"},a.SAFE);a.add({test:!Array.from||!Array.of,uri:"es6.array"},a.SAFE);a.add({test:!Math.acosh||!Math.asinh||!Math.atanh||!Math.cosh||!Math.sinh||!Math.tanh||!Math.expm1,uri:"es6.math"},a.SAFE);a.add({test:!Number.isFinite||!Number.isInteger||!Number.isNaN||!Number.toInteger,
uri:"es6.number"},a.SAFE);a.add({test:!Object.getOwnPropertyDescriptors||!Object.getPropertyDescriptor||!Object.getPropertyNames||!Object.is||!Object.isnt,uri:"es6.object"},a.SAFE);a.add({test:!String.prototype.repeat||!String.prototype.startsWith||!String.prototype.endsWith||!String.prototype.contains,uri:"es6.string"},a.SAFE);setTimeout(function(a){if(!a){var b=window.setTimeout;window.setTimeout=function(a,c){var d=Array.prototype.slice.call(arguments);d.shift();d.shift();b(function(){a.apply(this,
d)},c)}}},1,true)}).apply(this);
